---

_You are currently looking at **version 1.2** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 2 - Pandas
All questions are weighted the same in this assignment.
## Part 1
The following code loads the olympics dataset (olympics.csv), which was derrived from the Wikipedia entry on [All Time Olympic Games Medals](https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table), and does some basic data cleaning. 

The columns are organized as # of Summer games, Summer medals, # of Winter games, Winter medals, total # number of games, total # of medals. Use this dataset to answer the questions below.

In [233]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

# Summer  Gold  Silver  Bronze  Total  # Winter  Gold.1  \
Afghanistan        13     0       0       2      2         0       0   
Algeria            12     5       2       8     15         3       0   
Argentina          23    18      24      28     70        18       0   
Armenia             5     1       2       9     12         6       0   
Australasia         2     3       4       5     12         0       0   

             Silver.1  Bronze.1  Total.1  # Games  Gold.2  Silver.2  Bronze.2  \
Afghanistan         0         0        0       13       0         0         2   
Algeria             0         0        0       15       5         2         8   
Argentina           0         0        0       41      18        24        28   
Armenia             0         0        0       11       1         2         9   
Australasia         0         0        0        2       3         4         5   

             Combined total   ID  
Afghanistan               2  AFG  
Algeria                  15  ALG  
Argentina                70  ARG  
Armenia                  12  ARM  
Australasia              12  ANZ

### Question 0 (Example)

What is the first country in df?

*This function should return a Series.*

In [234]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.iloc[0]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero() 

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

### Question 1
Which country has won the most gold medals in summer games?

*This function should return a single string value.*

In [235]:
def answer_one():
    return df['Gold'].idxmax()

answer_one()

'United States'

### Question 2
Which country had the biggest difference between their summer and winter gold medal counts?

*This function should return a single string value.*

In [236]:
def answer_two():
    return abs(df['Gold'] - df['Gold.1']).idxmax()

answer_two()

'United States'

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [237]:
df_medals = df[(df['Gold'] > 0) & (df['Gold.1'] > 0)].copy()

In [238]:
df_medals

# Summer  Gold  Silver  Bronze  Total  # Winter  \
Australia                     25   139     152     177    468        18   
Austria                       26    18      33      35     86        22   
Belarus                        5    12      24      39     75         6   
Belgium                       25    37      52      53    142        20   
Bulgaria                      19    51      85      78    214        19   
Canada                        25    59      99     121    279        22   
China                          9   201     146     126    473        10   
Croatia                        6     6       7      10     23         7   
Czech Republic                 5    14      15      15     44         6   
Czechoslovakia                16    49      49      45    143        16   
Estonia                       11     9       9      15     33         9   
Finland                       24   101      84     117    302        22   
France                        27   202     223     246    671        22   
Germany                       15   174     182     217    573        11   
United Team of Germany         3    28      54      36    118         3   
East Germany                   5   153     129     127    409         6   
West Germany                   5    56      67      81    204         6   
Great Britain                 27   236     272     272    780        22   
Italy                         26   198     166     185    549        22   
Japan                         21   130     126     142    398        20   
Kazakhstan                     5    16      17      19     52         6   
South Korea                   16    81      82      80    243        17   
Netherlands                   25    77      85     104    266        20   
Norway                        24    56      49      43    148        22   
Poland                        20    64      82     125    271        22   
Russia                         5   132     121     142    395         6   
Soviet Union                   9   395     319     296   1010         9   
Unified Team                   1    45      38      29    112         1   
Slovakia                       5     7       9       8     24         6   
Slovenia                       6     4       6       9     19         7   
Spain                         22    37      59      35    131        19   
Sweden                        26   143     164     176    483        22   
Switzerland                   27    47      73      65    185        22   
Ukraine                        5    33      27      55    115         6   
United States                 26   976     757     666   2399        22   
Uzbekistan                     5     5       5      10     20         6   

                        Gold.1  Silver.1  Bronze.1  Total.1  # Games  Gold.2  \
Australia                    5         3         4       12       43     144   
Austria                     59        78        81      218       48      77   
Belarus                      6         4         5       15       11      18   
Belgium                      1         1         3        5       45      38   
Bulgaria                     1         2         3        6       38      52   
Canada                      62        56        52      170       47     121   
China                       12        22        19       53       19     213   
Croatia                      4         6         1       11       13      10   
Czech Republic               7         9         8       24       11      21   
Czechoslovakia               2         8        15       25       32      51   
Estonia                      4         2         1        7       20      13   
Finland                     42        62        57      161       46     143   
France                      31        31        47      109       49     233   
Germany                     78        78        53      209       26     252   
United Team of Germany       8         6        

In [239]:
def answer_three():
    return ((df_medals['Gold'] - df_medals['Gold.1']) / df_medals['Gold.2']).idxmax()

answer_three()

'Bulgaria'

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (`Gold.2`) counts for 3 points, silver medals (`Silver.2`) for 2 points, and bronze medals (`Bronze.2`) for 1 point. The function should return only the column (a Series object) which you created, with the country names as indices.

*This function should return a Series named `Points` of length 146*

In [240]:
def answer_four():
    df['Points'] = 3*df['Gold.2'] + 2*df['Silver.2'] + df['Bronze.2']
    return df['Points']

answer_four()

Afghanistan                            2
Algeria                               27
Argentina                            130
Armenia                               16
Australasia                           22
Australia                            923
Austria                              569
Azerbaijan                            43
Bahamas                               24
Bahrain                                1
Barbados                               1
Belarus                              154
Belgium                              276
Bermuda                                1
Bohemia                                5
Botswana                               2
Brazil                               184
British West Indies                    2
Bulgaria                             411
Burundi                                3
Cameroon                              12
Canada                               846
Chile                                 24
China                               1120
Colombia        

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2015/co-est2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

In [241]:
census_df = pd.read_csv('census.csv')
census_df.head()

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
0      40       3         6      1       0  Alabama         Alabama   
1      50       3         6      1       1  Alabama  Autauga County   
2      50       3         6      1       3  Alabama  Baldwin County   
3      50       3         6      1       5  Alabama  Barbour County   
4      50       3         6      1       7  Alabama     Bibb County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010     ...       \
0        4779736            4780127          4785161     ...        
1          54571              54571            54660     ...        
2         182265             182265           183193     ...        
3          27457              27457            27341     ...        
4          22915              22919            22861     ...        

   RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
0          0.002295         -0.193196          0.381066          0.582002   
1          7.242091         -2.915927         -3.012349          2.265971   
2         14.832960         17.647293         21.845705         19.243287   
3         -4.728132         -2.500690         -7.056824         -3.904217   
4         -5.527043         -5.068871         -6.201001         -0.177537   

   RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
0         -0.467369     1.030015     0.826644     1.383282     1.724718   
1         -2.530799     7.606016    -2.626146    -2.722002     2.592270   
2         17.197872    15.844176    18.559627    22.727626    20.317142   
3        -10.543299    -4.874741    -2.758113    -7.167664    -3.978583   
4          0.177258    -5.088389    -4.363636    -5.403729     0.754533   

   RNETMIG2015  
0     0.712594  
1    -2.187333  
2    18.293499  
3   -10.543299  
4     1.107861  

[5 rows x 100 columns]

In [242]:
census_df.groupby(['STNAME']).count()['COUNTY'].idxmax()

'Texas'

In [243]:
def answer_five():
    return census_df.groupby(['STNAME']).count()['COUNTY'].idxmax()

answer_five()

'Texas'

In [244]:
census_df.head()

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
0      40       3         6      1       0  Alabama         Alabama   
1      50       3         6      1       1  Alabama  Autauga County   
2      50       3         6      1       3  Alabama  Baldwin County   
3      50       3         6      1       5  Alabama  Barbour County   
4      50       3         6      1       7  Alabama     Bibb County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010     ...       \
0        4779736            4780127          4785161     ...        
1          54571              54571            54660     ...        
2         182265             182265           183193     ...        
3          27457              27457            27341     ...        
4          22915              22919            22861     ...        

   RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
0          0.002295         -0.193196          0.381066          0.582002   
1          7.242091         -2.915927         -3.012349          2.265971   
2         14.832960         17.647293         21.845705         19.243287   
3         -4.728132         -2.500690         -7.056824         -3.904217   
4         -5.527043         -5.068871         -6.201001         -0.177537   

   RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
0         -0.467369     1.030015     0.826644     1.383282     1.724718   
1         -2.530799     7.606016    -2.626146    -2.722002     2.592270   
2         17.197872    15.844176    18.559627    22.727626    20.317142   
3        -10.543299    -4.874741    -2.758113    -7.167664    -3.978583   
4          0.177258    -5.088389    -4.363636    -5.403729     0.754533   

   RNETMIG2015  
0     0.712594  
1    -2.187333  
2    18.293499  
3   -10.543299  
4     1.107861  

[5 rows x 100 columns]

In [245]:
census_df50 = census_df[census_df['SUMLEV'] == 50]
census_df50.head()

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
1      50       3         6      1       1  Alabama  Autauga County   
2      50       3         6      1       3  Alabama  Baldwin County   
3      50       3         6      1       5  Alabama  Barbour County   
4      50       3         6      1       7  Alabama     Bibb County   
5      50       3         6      1       9  Alabama   Blount County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010     ...       \
1          54571              54571            54660     ...        
2         182265             182265           183193     ...        
3          27457              27457            27341     ...        
4          22915              22919            22861     ...        
5          57322              57322            57373     ...        

   RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
1          7.242091         -2.915927         -3.012349          2.265971   
2         14.832960         17.647293         21.845705         19.243287   
3         -4.728132         -2.500690         -7.056824         -3.904217   
4         -5.527043         -5.068871         -6.201001         -0.177537   
5          1.807375         -1.177622         -1.748766         -2.062535   

   RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
1         -2.530799     7.606016    -2.626146    -2.722002     2.592270   
2         17.197872    15.844176    18.559627    22.727626    20.317142   
3        -10.543299    -4.874741    -2.758113    -7.167664    -3.978583   
4          0.177258    -5.088389    -4.363636    -5.403729     0.754533   
5         -1.369970     1.859511    -0.848580    -1.402476    -1.577232   

   RNETMIG2015  
1    -2.187333  
2    18.293499  
3   -10.543299  
4     1.107861  
5    -0.884411  

[5 rows x 100 columns]

In [246]:
census_df50 = census_df50.set_index(['STNAME', 'CTYNAME'])
census_df50.head()

SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STNAME  CTYNAME                                                   
Alabama Autauga County      50       3         6      1       1   
        Baldwin County      50       3         6      1       3   
        Barbour County      50       3         6      1       5   
        Bibb County         50       3         6      1       7   
        Blount County       50       3         6      1       9   

                        CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  \
STNAME  CTYNAME                                                             
Alabama Autauga County          54571              54571            54660   
        Baldwin County         182265             182265           183193   
        Barbour County          27457              27457            27341   
        Bibb County             22915              22919            22861   
        Blount County           57322              57322            57373   

                        POPESTIMATE2011  POPESTIMATE2012     ...       \
STNAME  CTYNAME                                              ...        
Alabama Autauga County            55253            55175     ...        
        Baldwin County           186659           190396     ...        
        Barbour County            27226            27159     ...        
        Bibb County               22733            22642     ...        
        Blount County             57711            57776     ...        

                        RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  \
STNAME  CTYNAME                                                                
Alabama Autauga County          7.242091         -2.915927         -3.012349   
        Baldwin County         14.832960         17.647293         21.845705   
        Barbour County         -4.728132         -2.500690         -7.056824   
        Bibb County            -5.527043         -5.068871         -6.201001   
        Blount County           1.807375         -1.177622         -1.748766   

                        RDOMESTICMIG2014  RDOMESTICMIG2015  RNETMIG2011  \
STNAME  CTYNAME                                                           
Alabama Autauga County          2.265971         -2.530799     7.606016   
        Baldwin County         19.243287         17.197872    15.844176   
        Barbour County         -3.904217        -10.543299    -4.874741   
        Bibb County            -0.177537          0.177258    -5.088389   
        Blount County          -2.062535         -1.369970     1.859511   

                        RNETMIG2012  RNETMIG2013  RNETMIG2014  RNETMIG2015  
STNAME  CTYNAME                                                             
Alabama Autauga County    -2.626146    -2.722002     2.592270    -2.187333  
        Baldwin County    18.559627    22.727626    20.317142    18.293499  
        Barbour County    -2.758113    -7.167664    -3.978583   -10.543299  
        Bibb County       -4.363636    -5.403729     0.754533     1.107861  
        Blount County     -0.848580    -1.402476    -1.577232    -0.884411  

[5 rows x 98 columns]

In [247]:
#census_df50.loc['Alabama']['CENSUS2010POP']

### Question 6
**Only looking at the three most populous counties for each state**, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [248]:
def answer_six():
    vals = census_df50.sort_values(by = ['CENSUS2010POP'], ascending = [False])[:3].index.values
    soln = []
    for val in vals:
        soln.append(val[0])
    return soln

answer_six()

['California', 'Illinois', 'Texas']

### Question 7
Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

In [249]:
fieldList = ['POPESTIMATE2010', 'POPESTIMATE2011', 'POPESTIMATE2012', 'POPESTIMATE2013', 'POPESTIMATE2014', 'POPESTIMATE2015']
census_dfpop = census_df50[fieldList]
census_dfpop.head(15)

POPESTIMATE2010  POPESTIMATE2011  POPESTIMATE2012  \
STNAME  CTYNAME                                                              
Alabama Autauga County             54660            55253            55175   
        Baldwin County            183193           186659           190396   
        Barbour County             27341            27226            27159   
        Bibb County                22861            22733            22642   
        Blount County              57373            57711            57776   
        Bullock County             10887            10629            10606   
        Butler County              20944            20673            20408   
        Calhoun County            118437           117768           117286   
        Chambers County            34098            33993            34075   
        Cherokee County            25976            26080            26023   
        Chilton County             43665            43739            43697   
        Choctaw County             13841            13593            13543   
        Clarke County              25767            25570            25144   
        Clay County                13880            13670            13456   
        Cleburne County            14973            14971            14921   

                         POPESTIMATE2013  POPESTIMATE2014  POPESTIMATE2015  
STNAME  CTYNAME                                                             
Alabama Autauga County             55038            55290            55347  
        Baldwin County            195126           199713           203709  
        Barbour County             26973            26815            26489  
        Bibb County                22512            22549            22583  
        Blount County              57734            57658            57673  
        Bullock County             10628            10829            10696  
        Butler County              20261            20276            20154  
        Calhoun County            116575           115993           115620  
        Chambers County            34153            34052            34123  
        Cherokee County            26084            25995            25859  
        Chilton County             43795            43921            43943  
        Choctaw County             13378            13289            13170  
        Clarke County              25116            24847            24675  
        Clay County                13467            13538            13555  
        Cleburne County            15028            15072            15018

In [250]:
def calc_diff(row):
    return max(row) - min(row)

In [251]:
census_dfpop.apply(calc_diff, axis=1).sort_values(ascending=False).idxmax()[1]

'Harris County'

In [252]:
def answer_seven():   
    return census_dfpop.apply(calc_diff, axis=1).sort_values(ascending=False).idxmax()[1]

answer_seven()

'Harris County'

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [253]:
census_df50.head(10)

SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STNAME  CTYNAME                                                    
Alabama Autauga County       50       3         6      1       1   
        Baldwin County       50       3         6      1       3   
        Barbour County       50       3         6      1       5   
        Bibb County          50       3         6      1       7   
        Blount County        50       3         6      1       9   
        Bullock County       50       3         6      1      11   
        Butler County        50       3         6      1      13   
        Calhoun County       50       3         6      1      15   
        Chambers County      50       3         6      1      17   
        Cherokee County      50       3         6      1      19   

                         CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  \
STNAME  CTYNAME                                                              
Alabama Autauga County           54571              54571            54660   
        Baldwin County          182265             182265           183193   
        Barbour County           27457              27457            27341   
        Bibb County              22915              22919            22861   
        Blount County            57322              57322            57373   
        Bullock County           10914              10915            10887   
        Butler County            20947              20946            20944   
        Calhoun County          118572             118586           118437   
        Chambers County          34215              34170            34098   
        Cherokee County          25989              25986            25976   

                         POPESTIMATE2011  POPESTIMATE2012     ...       \
STNAME  CTYNAME                                               ...        
Alabama Autauga County             55253            55175     ...        
        Baldwin County            186659           190396     ...        
        Barbour County             27226            27159     ...        
        Bibb County                22733            22642     ...        
        Blount County              57711            57776     ...        
        Bullock County             10629            10606     ...        
        Butler County              20673            20408     ...        
        Calhoun County            117768           117286     ...        
        Chambers County            33993            34075     ...        
        Cherokee County            26080            26023     ...        

                         RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  \
STNAME  CTYNAME                                                                 
Alabama Autauga County           7.242091         -2.915927         -3.012349   
        Baldwin County          14.832960         17.647293         21.845705   
        Barbour County          -4.728132         -2.500690         -7.056824   
        Bibb County             -5.527043         -5.068871         -6.201001   
        Blount County            1.807375         -1.177622         -1.748766   
        Bullock County         -30.953709         -5.180127         -1.130263   
        Butler County          -14.032727        -11.684234         -5.655413   
        Calhoun County          -6.155670         -4.611706         -5.524649   
        Chambers County         -2.731639          3.849092          2.872721   
        Cherokee County          6.339327          1.113180          5.488706   

                         RDOMESTICMIG2014  RDOMESTICMIG2015  RNETMIG2011  \
STNAME  CTYNAME                                                            
Alabama Autauga County           2.265971         -2.530799     7.606016   
        Baldwin County          19.243287         17.197872    15.844176   
        Barbour County          -3.904217        -10.543299    -4.874741   
        Bibb County          

In [254]:
# census_df50.index.values[0][1][:10] == 'Washington'

census_df50.loc[[val for val in census_df50.index.values if val[1][:10]=='Washington']]

SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STNAME         CTYNAME                                                      
Alabama        Washington County      50       3         6      1     129   
Arkansas       Washington County      50       3         7      5     143   
Colorado       Washington County      50       4         8      8     121   
Florida        Washington County      50       3         5     12     133   
Georgia        Washington County      50       3         5     13     303   
Idaho          Washington County      50       4         8     16      87   
Illinois       Washington County      50       2         3     17     189   
Indiana        Washington County      50       2         3     18     175   
Iowa           Washington County      50       2         4     19     183   
Kansas         Washington County      50       2         4     20     201   
Kentucky       Washington County      50       3         6     21     229   
Louisiana      Washington Parish      50       3         7     22     117   
Maine          Washington County      50       1         1     23      29   
Maryland       Washington County      50       3         5     24      43   
Minnesota      Washington County      50       2         4     27     163   
Mississippi    Washington County      50       3         6     28     151   
Missouri       Washington County      50       2         4     29     221   
Nebraska       Washington County      50       2         4     31     177   
New York       Washington County      50       1         2     36     115   
North Carolina Washington County      50       3         5     37     187   
Ohio           Washington County      50       2         3     39     167   
Oklahoma       Washington County      50       3         7     40     147   
Oregon         Washington County      50       4         9     41      67   
Pennsylvania   Washington County      50       1         2     42     125   
Rhode Island   Washington County      50       1         1     44       9   
Tennessee      Washington County      50       3         6     47     179   
Texas          Washington County      50       3         7     48     477   
Utah           Washington County      50       4         8     49      53   
Vermont        Washington County      50       1         1     50      23   
Virginia       Washington County      50       3         5     51     191   
Wisconsin      Washington County      50       2         3     55     131   

                                  CENSUS2010POP  ESTIMATESBASE2010  \
STNAME         CTYNAME                                               
Alabama        Washington County          17581              17583   
Arkansas       Washington County         203065             203060   
Colorado       Washington County           4814               4814   
Florida        Washington County          24896              24896   
Georgia        Washington County          21187              21187   
Idaho          Washington County          10198              10198   
Illinois       Washington County          14716              14716   
Indiana        Washington County          28262              28262   
Iowa           Washington County          21704              21704   
Kansas         Washington County           5799               5799   
Kentucky       Washington County          11717              11717   
Louisiana      Washington Parish          47168              47171   
Maine          Washington County          32856              32856   
Maryland       Washington County         147430             147430   
Minnesota      Washington County         238136             238134   
Mississippi    Washington County          51137              51135   
Missouri       Washington County          25195              25196   
Nebraska       Washington County          20234              20234   
New York       Washington County          63216              63216   
North Carolina Washing

In [255]:
# Using original df
census_df[census_df['CTYNAME'].str.contains('^Washington')]

# census_df50[census_df50['CTYNAME'].str.contains('^Washington')]

SUMLEV  REGION  DIVISION  STATE  COUNTY          STNAME  \
65        50       3         6      1     129         Alabama   
186       50       3         7      5     143        Arkansas   
311       50       4         8      8     121        Colorado   
396       50       3         5     12     133         Florida   
547       50       3         5     13     303         Georgia   
607       50       4         8     16      87           Idaho   
703       50       2         3     17     189        Illinois   
799       50       2         3     18     175         Indiana   
896       50       2         4     19     183            Iowa   
1005      50       2         4     20     201          Kansas   
1125      50       3         6     21     229        Kentucky   
1190      50       3         7     22     117       Louisiana   
1211      50       1         1     23      29           Maine   
1234      50       3         5     24      43        Maryland   
1419      50       2         4     27     163       Minnesota   
1501      50       3         6     28     151     Mississippi   
1618      50       2         4     29     221        Missouri   
1770      50       2         4     31     177        Nebraska   
1918      50       1         2     36     115        New York   
2017      50       3         5     37     187  North Carolina   
2162      50       2         3     39     167            Ohio   
2241      50       3         7     40     147        Oklahoma   
2279      50       4         9     41      67          Oregon   
2345      50       1         2     42     125    Pennsylvania   
2355      50       1         1     44       9    Rhode Island   
2560      50       3         6     47     179       Tennessee   
2805      50       3         7     48     477           Texas   
2848      50       4         8     49      53            Utah   
2863      50       1         1     50      23         Vermont   
2957      50       3         5     51     191        Virginia   
3000      40       4         9     53       0      Washington   
3163      50       2         3     55     131       Wisconsin   

                CTYNAME  CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  \
65    Washington County          17581              17583            17610   
186   Washington County         203065             203060           204026   
311   Washington County           4814               4814             4801   
396   Washington County          24896              24896            24754   
547   Washington County          21187              21187            21110   
607   Washington County          10198              10198            10195   
703   Washington County          14716              14716            14701   
799   Washington County          28262              28262            28284   
896   Washington County          21704              21704            21697   
1005  Washington County           5799               5799             5782   
1125  Washington County          11717              11717            11742   
1190  Washington Parish          47168              47171            47099   
1211  Washington County          32856              32856            32824   
1234  Washington County         147430             147430           147738   
1419  Washington County         238136             238134           238995   
1501  Washington County          51137              51135            51076   
1618  Washington County          25195              25196            25177   
1770  Washington County          20234              20234            20275   
1918  Washington County          63216              63216            63292   
2017  Washington County          13228              13218            13163   
2162  Washington County          61778              61778            61708   
2241  Washington County          50976              50977            51064   
2279  Washington County         529710             529849         

In [256]:
query = ((census_df50['REGION'] == 1) | (census_df50['REGION'] == 2))
census_df50[query]

SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STNAME      CTYNAME                                                       
Connecticut Fairfield County        50       1         1      9       1   
            Hartford County         50       1         1      9       3   
            Litchfield County       50       1         1      9       5   
            Middlesex County        50       1         1      9       7   
            New Haven County        50       1         1      9       9   
            New London County       50       1         1      9      11   
            Tolland County          50       1         1      9      13   
            Windham County          50       1         1      9      15   
Illinois    Adams County            50       2         3     17       1   
            Alexander County        50       2         3     17       3   
            Bond County             50       2         3     17       5   
            Boone County            50       2         3     17       7   
            Brown County            50       2         3     17       9   
            Bureau County           50       2         3     17      11   
            Calhoun County          50       2         3     17      13   
            Carroll County          50       2         3     17      15   
            Cass County             50       2         3     17      17   
            Champaign County        50       2         3     17      19   
            Christian County        50       2         3     17      21   
            Clark County            50       2         3     17      23   
            Clay County             50       2         3     17      25   
            Clinton County          50       2         3     17      27   
            Coles County            50       2         3     17      29   
            Cook County             50       2         3     17      31   
            Crawford County         50       2         3     17      33   
            Cumberland County       50       2         3     17      35   
            DeKalb County           50       2         3     17      37   
            De Witt County          50       2         3     17      39   
            Douglas County          50       2         3     17      41   
            DuPage County           50       2         3     17      43   
...                                ...     ...       ...    ...     ...   
Wisconsin   Oconto County           50       2         3     55      83   
            Oneida County           50       2         3     55      85   
            Outagamie County        50       2         3     55      87   
            Ozaukee County          50       2         3     55      89   
            Pepin County            50       2         3     55      91   
            Pierce County           50       2         3     55      93   
            Polk County             50       2         3     55      95   
            Portage County          50       2         3     55      97   
            Price County            50       2         3     55      99   
            Racine County           50       2         3     55     101   
            Richland County         50       2         3     55     103   
            Rock County             50       2         3     55     105   
            Rusk County             50       2         3     55     107   
            St. Croix County        50       2         3     55     109   
            Sauk County             50       2         3     55     111   
            Sawyer County           50       2         3     55     113   
            Shawano County          50       2         3     55     115   
            Sheboygan County        50       2         3     55     117   
            Taylor County           50       2         3     55     119   
            Trempealeau County      50       2         3     55     121   
            Vernon County           50       2         3 

In [257]:
# Approach 1
# def answer_eight():
#     census_washington = census_df50.loc[[val for val in census_df50.index.values if val[1][:10]=='Washington']]
#     query = ((census_washington['REGION'] == 1) | (census_washington['REGION'] == 2)) & \
#     (census_washington['POPESTIMATE2015'] > census_washington['POPESTIMATE2014'])
#     return census_washington[query]

# Approach 2
def answer_eight():
    query = ((census_df['REGION'] == 1) | (census_df['REGION'] == 2)) & \
        (census_df['POPESTIMATE2015'] > census_df['POPESTIMATE2014']) & \
        (census_df['CTYNAME'].str.contains('^Washington')) & \
        (census_df['SUMLEV'] == 50)
    return census_df[query][['STNAME', 'CTYNAME']]

answer_eight()

STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County

In [258]:
census_df.head()

SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
0      40       3         6      1       0  Alabama         Alabama   
1      50       3         6      1       1  Alabama  Autauga County   
2      50       3         6      1       3  Alabama  Baldwin County   
3      50       3         6      1       5  Alabama  Barbour County   
4      50       3         6      1       7  Alabama     Bibb County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010     ...       \
0        4779736            4780127          4785161     ...        
1          54571              54571            54660     ...        
2         182265             182265           183193     ...        
3          27457              27457            27341     ...        
4          22915              22919            22861     ...        

   RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  \
0          0.002295         -0.193196          0.381066          0.582002   
1          7.242091         -2.915927         -3.012349          2.265971   
2         14.832960         17.647293         21.845705         19.243287   
3         -4.728132         -2.500690         -7.056824         -3.904217   
4         -5.527043         -5.068871         -6.201001         -0.177537   

   RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  RNETMIG2013  RNETMIG2014  \
0         -0.467369     1.030015     0.826644     1.383282     1.724718   
1         -2.530799     7.606016    -2.626146    -2.722002     2.592270   
2         17.197872    15.844176    18.559627    22.727626    20.317142   
3        -10.543299    -4.874741    -2.758113    -7.167664    -3.978583   
4          0.177258    -5.088389    -4.363636    -5.403729     0.754533   

   RNETMIG2015  
0     0.712594  
1    -2.187333  
2    18.293499  
3   -10.543299  
4     1.107861  

[5 rows x 100 columns]

In [259]:
query = ((census_df['REGION'] == 1) | (census_df['REGION'] == 2)) & \
        (census_df['POPESTIMATE2015'] > census_df['POPESTIMATE2014']) & \
        (census_df['CTYNAME'].str.contains('^Washington')) & \
        (census_df['SUMLEV'] == 50)

census_df[query][['STNAME', 'CTYNAME']]

STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County